FROM node:8

RUN apt-get update && apt-get install -y build-essential && apt-get install -y python
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/package.json
RUN npm install
COPY . /usr/src/app

ENV NODE_ENV="dev"
ENV MONGO_URI = "mongodb://host.docker.internal:27017/cafe"
ENV TOKEN_SEED = "sid-de-dev-docker"

CMD ["npm", "start"]

EXPOSE 3001
EXPOSE 27017
